name: deafrica-conflux-env
channels:
  - conda-forge
dependencies:
  - python = 3.10.6 
  - gdal = 3.6.3 
  - pip:
    - --extra-index-url="https://packages.dea.ga.gov.au"
    - pip-tools
    - boto3
    - botocore
    - boto3-stubs[s3,sqs]
    - click
    - datacube
    - fsspec
    - python-geohash
    - geopandas
    - numpy
    - pandas
    - rasterio
    - shapely
    - SQLAlchemy
    - s3urls
    - pyarrow
    - tqdm
    - xarray
    - s3fs
    - pyarrow
    - deafrica-tools>=2.0.1
    # Code style
    - flake8
    - black
    # Testing
    - pytest
