---
name: Lint

on: [push]

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - run: python -m pip install flake8
      - name: flake8 cleanup imported but unused
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: |
            flake8 .
