name: push-develop

on:
  push:
    branches:
      - develop
    paths:
      - 'dea_conflux/**'
      - 'examples/**'
      - '.github/workflows/push.yml'
      - 'Dockerfile'

env:
  IMAGE_NAME: geoscienceaustralia/dea-conflux
permissions:
 id-token: write
 contents: read
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get git commit hash for push to develop
      run: |
        git fetch --all --tags
        echo "RELEASE=$(git describe --tags)" >> $GITHUB_ENV
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::538673716275:role/dea-conflux_github-actions-role
        aws-region: ap-southeast-2
    - name: Push image to ECR with latest tag
      uses: whoan/docker-build-with-cache-action@master
      with:
        registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
        image_name: ${{ env.IMAGE_NAME }}
        image_tag: latest
        build_extra_args: '{"--build-arg": "UPDATE_VERSION=${{ env.RELEASE }}"}'
