name: Push development image

on:
  push:
    branches:
      - develop

env:
  IMAGE_NAME: geoscienceaustralia/dea-conflux
permissions:
 id-token: write
 contents: read
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get version for development build
      run: |
        git fetch --all --tags
        echo "RELEASE=$(git describe --tags)" >> $GITHUB_ENV
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        role-to-assume: arn:aws:iam::538673716275:role/dea-conflux_github-actions-role
        aws-region: ap-southeast-2
    - name: Push image to ECR with dev tag
      uses: whoan/docker-build-with-cache-action@master
      with:
        registry: 538673716275.dkr.ecr.ap-southeast-2.amazonaws.com
        image_name: ${{ env.IMAGE_NAME }}
        image_tag: dev
        build_extra_args: '{"--build-arg": "UPDATE_VERSION=${{ env.RELEASE }}"}'
