name: Test

on:
  workflow_dispatch:
  pull_request:

env:
  ORG: victorianeema
  IMAGE: deafrica-conflux
  PRODUCT_CATALOG: https://raw.githubusercontent.com/digitalearthafrica/config/master/prod/products_prod.csv

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0

    - name: Activate Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11  
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Setup deafrica-conflux test environment
      run: |
          make test-env

    - name: Run deafrica-conflux test
      run: |
          make run-tests
          make clean

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false

    - name: Clean deafrica-conflux image
      run: |
          (echo y) | docker container prune
          (echo y) | docker image prune
