name: Test

#on: [push]
on:
  pull_request

env:
  ORG: digitalearthafrica
  IMAGE: deafrica-conflux
  PRODUCT_CATALOG: https://raw.githubusercontent.com/digitalearthafrica/config/master/prod/products_prod.csv

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0

    - name: Activate Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.11  
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Setup deafrica-conflux test environment
      run: |
          make test-env

    - name: Run deafrica-conflux test
      run: |
          docker-compose exec -T conflux bash -c "coverage run -m pytest ."
          docker-compose exec -T conflux bash -c "coverage report -m"
          docker-compose exec -T conflux bash -c "coverage xml"
          docker-compose exec -T conflux bash -c "coverage html"
          make down

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false

    - name: Clean deafrica-conflux image
      run: |
          (echo y) | docker container prune
          (echo y) | docker image prune
