name: Test

on: [push]

env:
  ORG: geoscienceaustralia
  IMAGE: dea-conflux
  METADATA_CATALOG: https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml
  PRODUCT_CATALOG: https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/87ca056fa62900596cbf05612da9033fc763009c/workspaces/sandbox-products.csv

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pre-pull layers
      run: docker-compose pull

    - name: Activate Docker cache
      uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build dea-conflux image
      run: |
        docker-compose build

    - name: Test dea-conflux image
      run: |
          docker-compose up -d
          ./tests/setup_test_datacube.sh
          docker-compose exec -T conflux bash -c "pytest --cov-report=xml ."
          docker-compose down

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: false